services:
- docker
env:
  matrix:
  - COMPOSE_VERSION=3.9
  global:
  - secure: V0He4wzI0/mHF+gmRAArvwJ7RxellMwPY6gX3Cx9B3Bf5JT06lsSXnUaVDoneB6d0YcSOz34CijowoL09jwjXKe32cZ16GNcZBhY2UKDhbK38iDfU8dBcOfKdnzikUItQ4iW6LV47MT+rLsqTkOTg3tEOzEussUVpYYU8KDbRgmnf0TlxtdLG3mxYTaZkIwidVBdtoDkCUkJqNtrBloWB+mwrb++XdABNWNV7DXVJlHQOCTy88a2GVsTMDxbMsc7AW7zehKLe+6gq0m4F30TlZeG3OWyS8lm8LUoSG4ulNidSA2qiU8ZAi6Pg2YoNnMjVHUaR3JJeWHTaFb/y6XfXuEcdacYyNFKCK5B7Othy1lG6VZmn264KpUBZsvWaOq7y6U2+Yjc22XQ3iOc0ZxKeAZC5A1mq/Rlrt/rEfX+002wbqPSwLABt2WEcpqEIzFiY2L1306pL3EGx8hP8S37AHTr8MACi50TOEtLzKQj1qiWsx9RRmaNSclQ4SZyxasqyZw1LG8BhHEVyfOhGSLkQPTkPPHQ3n2aGV54knWnmjXyfRLCm5TjYg0n07zdGDwe/pPdUt0VcQtUfmfnoepiS9hK/l6wGZfS6nvd/S55C9+33tPTocmzUVqCMJvrojNMdrLnvr5xb5KNhX7kXA0U3stEiCc7UJAQCpq+ViMR3/4=
  - secure: Zb0hEEhGtFUaQT3KLa8ughwlRlzl2PQ8V5eQLBD1S4mpzy+BfeXLUzfPNAH2+Hcr8tUWyQBauLczruHLlIGIpgUrNoxY4igu7F1DP9tRnZ58O66vfOOdRvOFmkt2psilC1xs7L9OtwVzlSuqv6BlH4Oumw+NZ5Mng9Sd3e9nqMVbfQBwpGs836UXPhvVeGO26/hs0Wr3qKY6RZ9Ofj5jmZMq5mFdJCOP4/C6mHcGJsPTsIChkFyVHyfVXdtBup6Uf0ZeW/DiW4QmG7O+DxQ5X9gu2EbDnm4ksNrqpRjSN8MeBF5XQFggci1/O+W9Ls83W6ugktFPd+X22NiLqV85eC7DyDoNbaaOaQsyWlJFCAspGT/TdR/ec5dicD0hxCdkxiYZl1AHNklubwMWQxq1tHNUT6IzDIlVPHwxCwRpocj6rFvoj+kIa6x0YOrfX03pKjND6tUWOccX14bslNcV3tVPhCbZJSgJfksH/raFZIthLi6ZOse7nCuUSbeq1VqPqovW7KQZgzJn2v6SNGLOAYtkmaX5Vkt5ictOF5vFmVcODwx5Hh9qDktIJGJFJzd3j8B1iumjDNqFDbHxLrzx5zRIpDRvVjMOkGdK+Uq3MDS+f7awe+IWsbvzM/m6vAgx5oHnqYshIo1kP51Yrm4HF3gI1iYSx5u8I05vkD4+mdk=
script:
- export APP_KEY=$APP_KEY
- export TOKEN=$TOKEN
- docker build --target test --tag todo.app:test .
- docker run --mount type=bind,source="$(pwd)"/todo_app,target=/srv/todo_app todo.app:test
