services:
  - docker

env:
 - COMPOSE_VERSION=3.9

script:
- docker build --target test --tag todo.app:test .
# Unit & integration tests
- docker run --mount type=bind,source="$(pwd)"/todo_app,target=/srv/todo_app todo.app:test